// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dwiwloyahzkqamkbwvrq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR3aXdsb3lhaHprcWFta2J3dnJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwODUxNjcsImV4cCI6MjA2OTY2MTE2N30.osIH20D4G94bO_Thn_d7_pWmkVQ0SY2XtTZ1ZjfRke8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});